In [20]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.neighbors import KNeighborsClassifier

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [14]:
bank = pd.read_csv("C:\Aalesh and Mandar\Datasets\Bankruptcy.csv")
test = pd.read_csv(r"C:\Aalesh and Mandar\Datasets\testBankruptcy.csv")

In [15]:
bank.head()

,NO,D,YR,R1,R2,R3,R4,R5,R6,R7,...,R15,R16,R17,R18,R19,R20,R21,R22,R23,R24
0,1,0,78,0.23,0.08,0.02,0.03,0.46,0.12,0.19,...,0.05,0.57,0.15,0.23,3.56,0.26,1.55,0.43,0.11,0.17
1,2,0,77,0.19,0.07,0.09,0.12,0.02,0.02,0.03,...,0.09,0.12,0.16,0.22,3.78,1.29,1.40,0.06,0.07,0.10
2,3,0,72,0.07,0.02,0.03,0.05,0.06,0.10,0.14,...,-0.03,0.02,0.02,0.04,13.29,1.61,1.43,0.03,0.05,0.07
3,4,0,80,0.07,0.03,0.04,0.04,0.04,0.06,0.06,...,-0.02,0.01,0.02,0.02,5.36,1.30,1.12,-0.06,-0.08,-0.09
4,5,0,81,0.09,0.02,0.03,0.04,0.06,0.08,0.11,...,0.02,0.07,0.10,0.14,7.74,1.48,1.41,0.03,0.04,0.06

In [16]:
bank = bank.drop("NO", axis=1)
bank = bank.drop("YR", axis=1)
bank.head()

,D,R1,R2,R3,R4,R5,R6,R7,R8,R9,...,R15,R16,R17,R18,R19,R20,R21,R22,R23,R24
0,0,0.23,0.08,0.02,0.03,0.46,0.12,0.19,10.36,1.17,...,0.05,0.57,0.15,0.23,3.56,0.26,1.55,0.43,0.11,0.17
1,0,0.19,0.07,0.09,0.12,0.02,0.02,0.03,3.13,1.73,...,0.09,0.12,0.16,0.22,3.78,1.29,1.40,0.06,0.07,0.10
2,0,0.07,0.02,0.03,0.05,0.06,0.10,0.14,2.41,1.36,...,-0.03,0.02,0.02,0.04,13.29,1.61,1.43,0.03,0.05,0.07
3,0,0.07,0.03,0.04,0.04,0.04,0.06,0.06,5.55,1.13,...,-0.02,0.01,0.02,0.02,5.36,1.30,1.12,-0.06,-0.08,-0.09
4,0,0.09,0.02,0.03,0.04,0.06,0.08,0.11,2.85,1.88,...,0.02,0.07,0.10,0.14,7.74,1.48,1.41,0.03,0.04,0.06

In [17]:
x = bank.drop("D", axis=1)
y = bank["D"]

In [18]:
knn = KNeighborsClassifier()
knn.fit(x,y)

KNeighborsClassifier()

In [19]:
test = test.drop("NO", axis=1)
test.head()

,R1,R2,R3,R4,R5,R6,R7,R8,R9,R10,...,R15,R16,R17,R18,R19,R20,R21,R22,R23,R24
0,0.16,0.08,0.06,0.08,0.03,0.02,0.03,1.46,2.74,0.75,...,0.01,0.08,0.06,0.08,4.39,0.740,1.35,0.09,0.06,-0.09
1,0.10,0.04,0.07,0.07,0.02,0.04,0.04,5.88,1.54,0.32,...,-0.08,-0.04,-0.07,-0.07,7.75,1.810,1.05,-0.03,-0.05,-0.06
2,0.06,0.04,0.30,0.05,-0.11,-0.08,-0.13,0.84,0.50,1.53,...,0.11,0.24,0.19,0.29,2.85,0.880,1.53,0.11,0.09,-0.04
3,0.26,0.03,0.07,0.20,0.07,-0.20,0.40,3.27,1.65,0.52,...,0.38,0.08,0.17,0.49,9.54,3.114,2.89,0.08,0.17,0.08
4,0.26,0.02,0.90,-0.14,0.07,-0.60,0.35,42.56,1.58,0.40,...,0.14,0.07,0.16,0.33,51.15,2.540,2.03,0.07,0.17,0.33

In [9]:
y_pred = knn.predict(test)
y_pred

C:\Users\admin\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

array([0, 0, 0, 0, 1, 1], dtype=int64)

In [23]:
params = {"n_neighbors": [1,3,5,7,9,11,13,15]}
knn = KNeighborsClassifier()
gcv = GridSearchCV(knn, param_grid=params, scoring = "roc_auc", cv=KFold)
gcv.fit(x,y)
print(gcv.best_params_)
print(gcv.best_score_)

AttributeError: 'DataFrame' object has no attribute 'n_splits'